# Generated by Django 5.2.8 on 2025-11-20 03:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Message title', max_length=200)),
                ('content', models.TextField(help_text='Message content')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the message was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the message was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the message is active/visible')),
                ('author', models.ForeignKey(help_text='Message author', on_delete=django.db.models.deletion.CASCADE, related_name='board_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
